
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgcwbcagwttyvsscqpqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnY3diY2Fnd3R0eXZzc2NxcHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjE0NjAsImV4cCI6MjA1ODI5NzQ2MH0.Ths3hdWJCALzR1vA3IFf8nERfuVSuGkj0I7u6mgk_3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
